CREATE TABLE prophylactic (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created DATE NOT NULL,
    updated DATE NULL DEFAULT NULL,
    history CHAR(100) NULL DEFAULT NULL,
    name CHAR(50) NULL DEFAULT NULL,
    surname CHAR(50) NULL DEFAULT NULL,
    gender CHAR(50) NULL DEFAULT NULL,
    birthday DATE NULL DEFAULT NULL,
    PRIMARY KEY (id) USING BTREE
);